name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  makefile:
    name: Run Makefile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Execute make
      run: make -C src
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Deli.H3VR
        path: src/Deli.H3VR/Deli.H3VR.deli
